#!/usr/bin/env bash
# Applies app-specific settings to the android/ folder generated by `flutter create`.
set -euo pipefail
cd "$(dirname "$0")/.."
M=android/app/src/main/AndroidManifest.xml

# Network (ML Kit model download, live sync with teacher server on local Wi-Fi)
grep -q 'android.permission.INTERNET' "$M" || \
  sed -i 's#<application#<uses-permission android:name="android.permission.INTERNET"/>\n    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>\n    <application#' "$M"
grep -q 'usesCleartextTraffic' "$M" || \
  sed -i 's#<application#<application android:usesCleartextTraffic="true"#' "$M"
# In-app updates: download the new APK and hand it to the system installer (FileProvider → cache/updates/)
grep -q 'REQUEST_INSTALL_PACKAGES' "$M" || \
  sed -i 's#<application#<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"/>\n    <application#' "$M"
grep -q 'pulinote_update_paths' "$M" || \
  sed -i 's#</application>#    <provider android:name="androidx.core.content.FileProvider" android:authorities="${applicationId}.updates" android:exported="false" android:grantUriPermissions="true">\n            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/pulinote_update_paths"/>\n        </provider>\n    </application>#' "$M"
mkdir -p android/app/src/main/res/xml
cat > android/app/src/main/res/xml/pulinote_update_paths.xml <<'XML'
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <cache-path name="updates" path="updates/" />
</paths>
XML

# App name
sed -i 's#android:label="[^"]*"#android:label="풀이노트"#' "$M"

# minSdk 24 (ML Kit + modern stylus APIs)
for G in android/app/build.gradle.kts android/app/build.gradle; do
  [ -f "$G" ] || continue
  sed -i -E 's/minSdk(Version)? *=? *flutter\.minSdkVersion/minSdk = 24/' "$G"
done

# Release: no R8 minify/shrink. R8 strips WorkManager's Room database (a dependency of ML Kit)
# and the app dies right at launch (androidx.work.impl.WorkDatabase could not be created).
for G in android/app/build.gradle.kts android/app/build.gradle; do
  [ -f "$G" ] || continue
  if [[ "$G" == *.kts ]]; then
    sed -i -E 's/^([[:space:]]*)signingConfig = signingConfigs\.getByName\("debug"\)/&\n\1isMinifyEnabled = false\n\1isShrinkResources = false/' "$G"
  else
    sed -i -E 's/^([[:space:]]*)signingConfig signingConfigs\.debug/&\n\1minifyEnabled false\n\1shrinkResources false/' "$G"
  fi
  grep -Eq 'isMinifyEnabled = false|minifyEnabled false' "$G" || { echo "ERROR: could not disable minify in $G"; cat "$G"; exit 1; }
  # FileProvider for in-app updates
  if ! grep -q 'androidx.core:core' "$G"; then
    if [[ "$G" == *.kts ]]; then
      printf '\ndependencies {\n    implementation("androidx.core:core:1.13.1")\n}\n' >> "$G"
    else
      printf "\ndependencies {\n    implementation 'androidx.core:core:1.13.1'\n}\n" >> "$G"
    fi
  fi
  echo "---- $G ----"; cat "$G"
done

# Launcher icons
if [ -d tools/icons/res ]; then
  cp -r tools/icons/res/* android/app/src/main/res/
fi

echo "---- patched manifest ----"
cat "$M"
grep -n "minSdk" android/app/build.gradle* || true

# Low-latency stylus: ask Android for unbuffered (un-batched) pen events → more points, less lag.
MA=$(find android/app/src/main -name MainActivity.kt | head -1)
if [ -n "$MA" ]; then
  PKG=$(grep -m1 '^package ' "$MA")
  cat > "$MA" <<KT
$PKG

import android.content.Intent
import android.net.Uri
import android.os.Build
import android.provider.Settings
import android.view.MotionEvent
import androidx.core.content.FileProvider
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel
import java.io.File

class MainActivity : FlutterActivity() {
    // In-app updates (lib/services/updater.dart)
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, "pulinote/update").setMethodCallHandler { call, result ->
            try {
                when (call.method) {
                    "versionCode" -> {
                        val info = packageManager.getPackageInfo(packageName, 0)
                        @Suppress("DEPRECATION")
                        val code = if (Build.VERSION.SDK_INT >= 28) info.longVersionCode.toInt() else info.versionCode
                        result.success(code)
                    }
                    "canInstall" -> result.success(
                        if (Build.VERSION.SDK_INT >= 26) packageManager.canRequestPackageInstalls() else true
                    )
                    "openInstallSettings" -> {
                        if (Build.VERSION.SDK_INT >= 26) {
                            startActivity(Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES, Uri.parse("package:" + packageName)))
                        }
                        result.success(true)
                    }
                    "install" -> {
                        val path = call.argument<String>("path")
                        if (path == null) {
                            result.success(false)
                        } else {
                            val uri = FileProvider.getUriForFile(this, packageName + ".updates", File(path))
                            val intent = Intent(Intent.ACTION_VIEW)
                                .setDataAndType(uri, "application/vnd.android.package-archive")
                                .addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_ACTIVITY_NEW_TASK)
                            startActivity(intent)
                            result.success(true)
                        }
                    }
                    else -> result.notImplemented()
                }
            } catch (e: Exception) {
                result.error("update", e.message, null)
            }
        }
    }

    override fun dispatchTouchEvent(ev: MotionEvent): Boolean {
        val action = ev.actionMasked
        // Low latency: ask for unbuffered (un-batched) pen events, also when a palm touched first.
        if (action == MotionEvent.ACTION_DOWN || action == MotionEvent.ACTION_POINTER_DOWN) {
            val tool = ev.getToolType(ev.actionIndex)
            if (tool == MotionEvent.TOOL_TYPE_STYLUS || tool == MotionEvent.TOOL_TYPE_ERASER) {
                window.decorView.requestUnbufferedDispatch(ev)
            }
        }
        // Some firmware reports the S Pen side button as BUTTON_SECONDARY; Flutter only maps
        // BUTTON_STYLUS_PRIMARY, so translate it (the app then switches to the eraser).
        val bs = ev.buttonState
        if ((bs and MotionEvent.BUTTON_SECONDARY) != 0 && (bs and MotionEvent.BUTTON_STYLUS_PRIMARY) == 0) {
            var stylus = false
            for (i in 0 until ev.pointerCount) {
                if (ev.getToolType(i) == MotionEvent.TOOL_TYPE_STYLUS) stylus = true
            }
            if (stylus) {
                val n = ev.pointerCount
                val props = Array(n) { MotionEvent.PointerProperties() }
                val coords = Array(n) { MotionEvent.PointerCoords() }
                for (i in 0 until n) {
                    ev.getPointerProperties(i, props[i])
                    ev.getPointerCoords(i, coords[i])
                }
                val copy = MotionEvent.obtain(
                    ev.downTime, ev.eventTime, ev.action, n, props, coords, ev.metaState,
                    bs or MotionEvent.BUTTON_STYLUS_PRIMARY, ev.xPrecision, ev.yPrecision,
                    ev.deviceId, ev.edgeFlags, ev.source, ev.flags
                )
                val handled = super.dispatchTouchEvent(copy)
                copy.recycle()
                return handled
            }
        }
        return super.dispatchTouchEvent(ev)
    }
}
KT
  echo "---- MainActivity ----"; cat "$MA"
fi
