#!/usr/bin/env bash
# Applies app-specific settings to the android/ folder generated by `flutter create`.
set -euo pipefail
cd "$(dirname "$0")/.."
M=android/app/src/main/AndroidManifest.xml

# Network (ML Kit model download, live sync with teacher server on local Wi-Fi)
grep -q 'android.permission.INTERNET' "$M" || \
  sed -i 's#<application#<uses-permission android:name="android.permission.INTERNET"/>\n    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>\n    <application#' "$M"
grep -q 'usesCleartextTraffic' "$M" || \
  sed -i 's#<application#<application android:usesCleartextTraffic="true"#' "$M"
# App name
sed -i 's#android:label="[^"]*"#android:label="풀이노트"#' "$M"

# minSdk 24 (ML Kit + modern stylus APIs)
for G in android/app/build.gradle.kts android/app/build.gradle; do
  [ -f "$G" ] || continue
  sed -i -E 's/minSdk(Version)? *=? *flutter\.minSdkVersion/minSdk = 24/' "$G"
done

# Launcher icons
if [ -d tools/icons/res ]; then
  cp -r tools/icons/res/* android/app/src/main/res/
fi

echo "---- patched manifest ----"
cat "$M"
grep -n "minSdk" android/app/build.gradle* || true
